services:
    app1:
        container_name: app1
        build:
            context: .
            dockerfile: Dockerfile
            target: build-development
        image: dockerized-php-supervisor:dev
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www/html
        ports:
            - 80:8080
            - 9001:9001
