services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
            target: build-development
        image: app:supervisor
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www/html
        ports:
            - 80:8080
            - 9001:9001
